-- Create a table for RSVPs
create table rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  dietary_requirements text,
  attending boolean default true
);

-- Set up Row Level Security (RLS)
-- Allow anyone to insert (since we have a public form with a shared code)
-- But maybe restrict reading to only authenticated users (or just leave it open for simplicity if using anon key heavily)
alter table rsvps enable row level security;

create policy "Enable insert for everyone" on rsvps
for insert with check (true);

create policy "Enable read access for everyone" on rsvps
for select using (true);
